### ISSUE TITLE
feature request: vue support

### ISSUE THREAD

**Issue by arnoson** [cr34t1ve/csvars#1]
Thanks for the great plugin!
Could you add vue support? I just looked at the code and it seems that I would just have to add `.vue` to the list? Can't test it right now. Could also look into to it and create a PR if it would be more complicated than adding the file extensions :)

**Comment by cr34t1ve** [comment]
Good point! I hadn't considered there would be more people using this😄
I'll be adding that. Thanks for pointing that out!

**Comment by cr34t1ve** [comment]
@arnoson Vue support added!
